// [
//   PLAYERS.EMPTY, PLAYERS.EMPTY, PLAYERS.EMPTY,
//   PLAYERS.EMPTY, PLAYERS.DOG, PLAYERS.EMPTY,
//   PLAYERS.EMPTY, PLAYERS.EMPTY, PLAYERS.EMPTY,
// ],
// [
//   PLAYERS.CAT, PLAYERS.EMPTY, PLAYERS.EMPTY,
//   PLAYERS.EMPTY, PLAYERS.DOG, PLAYERS.EMPTY,
//   PLAYERS.EMPTY, PLAYERS.EMPTY, PLAYERS.EMPTY,
// ],
// [
//   PLAYERS.CAT, PLAYERS.EMPTY, PLAYERS.EMPTY,
//   PLAYERS.EMPTY, PLAYERS.DOG, PLAYERS.DOG,
//   PLAYERS.EMPTY, PLAYERS.EMPTY, PLAYERS.EMPTY,
// ],
// [
//   PLAYERS.CAT, PLAYERS.EMPTY, PLAYERS.EMPTY,
//   PLAYERS.CAT, PLAYERS.DOG, PLAYERS.DOG,
//   PLAYERS.EMPTY, PLAYERS.EMPTY, PLAYERS.EMPTY,
// ],
// [
//   PLAYERS.CAT, PLAYERS.EMPTY, PLAYERS.DOG,
//   PLAYERS.CAT, PLAYERS.DOG, PLAYERS.DOG,
//   PLAYERS.EMPTY, PLAYERS.EMPTY, PLAYERS.EMPTY,
// ],
// [
//   PLAYERS.CAT, PLAYERS.EMPTY, PLAYERS.DOG,
//   PLAYERS.CAT, PLAYERS.DOG, PLAYERS.DOG,
//   PLAYERS.CAT, PLAYERS.EMPTY, PLAYERS.EMPTY,
// ],